#!/usr/bin/sh

bspc config normal_border_color			\#202020
bspc config active_border_color			\#777777
bspc config focused_border_color		\#dddddd
bspc config presel_feedback_color		\#dddddd

bspc config split_ratio					0.5

bspc config border_width				2
bspc config window_gap					20
bspc config top_padding					25

bspc config borderless_monocle			false
bspc config gapless_monocle				false
bspc config click_to_focus				any
bspc config swallow_first_click			true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config merge_overlapping_monitors	true

polybar_config=$HOME/.config/polybar/nvidia-config

bspc monitor DP-4 --reset-desktops 1 2 3 4 5

bspc rule --add Gimp follow=on state=floating
bspc rule --add xcalc state=floating
bspc rule --add mirage state=floating
bspc rule --add qemu state=floating
bspc rule --add cmake-gui state=floating
bspc rule --add gpick state=floating
bspc rule --add galculator state=floating
bspc rule --add Emacs state=tiled

feh --bg-fill $HOME/pics/snowy_trees.png
xsetroot -cursor_name left_ptr

killall polybar
polybar top -q -r -l error -c $polybar_config &

