#!/bin/sh

grey="\x01"
white="\x02"
green="\x04"
yellow="\x05"
cyan="\x06"
magenta="\x07"
red="\x08"

getMpd() {
        title="$(ncmpcpp --now-playing | cut -d " " -f2-)"
        if [[ $title ]]; then
                echo -ne "${cyan}\uE05C${grey}  ${title}"
        fi
}

getVolume() {
        volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
        mute="$(amixer get Master | tail -n1 | awk '{print $6}')"

        if [ $mute == "[off]" ]; then
                volume="0"
        fi

        if [ $volume -eq 0 ]; then
                icon="\uE04F"
        elif [ $volume -le 33 ]; then
                icon="\uE04E"
        elif [ $volume -le 66 ]; then
                icon="\uE050"
        else
                icon="\uE05D"
        fi

        echo -ne "${cyan}${icon}${grey}  ${volume}%"

}

getNet() {
        current="$(iwgetid -r)"
        quality="$(cat /proc/net/wireless | tail -n1 | awk '{ print $3 }' | cut -d "." -f1)"

        if [[ $quality -le 35 ]]; then
                icon="\uE047"
#        elif [ $quality -le 56 ]; then
#                icon="\uE04A"
        elif [[ $quality -le 70 ]]; then
                icon="\uE048"
        fi

        if [ $current ]; then
                echo -ne "${cyan}${icon}${grey}  ${current}"
        else
                icon="\uE09F"
                echo -ne "${red}${icon}${grey}  dis"
        fi
}

getBattery() {
        level="$(acpi | grep -i battery | awk '{ print $4 }' | cut -d '%' -f1)"
        charging="$(acpi | grep -i battery | awk '{ print $3 }' | cut -d ',' -f1)"
        color=$cyan

        if [ $charging == "Full" ]; then
                icon="\uE042"
        elif [ $charging == "Charging" ]; then
                icon="\uE040"
        else
                if [ $level -le 25 ]; then
                        color=$red
                        icon="\uE030"
                elif [ $level -le 50 ]; then
                        color=$yellow
                        icon="\uE031"
                elif [ $level -le 75 ]; then
                        icon="\uE032"
                else
                        icon="\uE033"
                fi
        fi
        echo -ne "${color}${icon}${grey}  ${level}%"
}

getDate() {
        echo -ne "${cyan}\uE015${grey}  $(date "+%I:%M %p")  ${cyan}\uE00E"
}

while true; do
        xsetroot -name "$(getMpd)   $(getVolume)   $(getNet)   $(getBattery)   $(getDate)" 
        sleep 1
done
