#!/bin/sh

weather="$(weather ${1} | cut -d ':' -f1 | cut -d ' ' -f2)"
dir="/home/rohan/pics/wallpaper/weather/"
echo $weather
while true; do
	case "$weather" in
		"Sunny")
			feh --bg-fill "${dir}Sunny2.png"
			;;
		"Rain")
			feh --bg-fill "${dir}Raining.png"
			;;
		"Snow")
			feh --bg-fill "${dir}Snowing2.png"
			;;
		"Cloudy")
			feh --bg-fill "${dir}Cloudy.png"
			;;
		*)
			feh --bg-fill "/home/rohan/pics/wallpaper/fibonacci_ruler.png"
	esac
	sleep 1h
done
